#!/bin/bash

echo "nasm -f elf64 -l myprintf.lst  myprintf.asm"
nasm -f elf64 -l myprintf.lst  myprintf.asm
echo "ld -s -o myprintf.out myprintf.o"
ld -s -o myprintf.out myprintf.o
echo "./myprintf.out"
./myprintf.out
