#!/bin/bash

echo "nasm -g -f elf64 -l myprintf.lst  myprintf.asm"
nasm -g -f elf64 -l myprintf.lst  myprintf.asm

echo "ld -o myprintf.out myprintf.o"
ld -o myprintf.out myprintf.o

echo "./myprintf.out"
./myprintf.out
